In [8]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import re 
import nltk
import string
from nltk.corpus import stopwords
#nltk.download('stopwords')


pd.set_option("display.max_colwidth", None)

In [9]:
# PARA ROTACIONAR GRÁFICO 3D
%matplotlib notebook

import pandas as pd
import numpy as np
from scipy.stats import norm, probplot
import statsmodels.api as sm
import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D

# Para ter melhor print
from IPython.display import display

In [10]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\jprfi\OneDrive\Área de Trabalho\CDADOS\Projeto 2\p2cdados

In [11]:
### Função utilitária para fazer a regressão com constante adicionada

def regress(Y,X):
    '''
    Y: coluna do DataFrame utilizada como variável resposta (TARGET)
    X: coluna(s) do DataFrame utilizadas como variável(is) explicativas (FEATURES)
    '''
    X_cp = sm.add_constant(X)
    model = sm.OLS(Y,X_cp)
    results = model.fit()
    
    return results

In [12]:
filename = 'Housing.xlsx'
teste = pd.read_excel(filename)
teste.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-12223,3788,410,8800,1290.0,3220,1260,83252,4526000,NEAR BAY
1,-12222,3786,210,70990,11060.0,24010,11380,83014,3585000,NEAR BAY
2,-12224,3785,520,14670,1900.0,4960,1770,72574,3521000,NEAR BAY
3,-12225,3785,520,12740,2350.0,5580,2190,56431,3413000,NEAR BAY
4,-12225,3785,520,16270,2800.0,5650,2590,38462,3422000,NEAR BAY

In [13]:
train = pd.read_excel(filename, sheet_name = 'Treinamento')
train.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-11705,3273,270,31840,5880.0,17630,5710,35529,1339000,NEAR OCEAN
1,-11703,3274,350,18780,4540.0,9910,4090,24345,1297000,NEAR OCEAN
2,-11704,3274,330,38800,7700.0,22880,8050,36848,1407000,NEAR OCEAN
3,-11702,3274,120,33010,9630.0,20000,8790,18594,1192000,NEAR OCEAN
4,-11704,3274,50,28780,7850.0,17270,7580,17179,1320000,NEAR OCEAN

In [15]:
X = train['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income']
Y = train['median_house_value']
regre = regres

# filtra_linhas_0 = teste['ocean_proximity'] == 'INLAND'
# inl = teste.loc[filtra_linhas_0, :]

# filtra_linhas_1 = teste['ocean_proximity'] == '<1H OCEAN'
# locean = teste.loc[filtra_linhas_1, :]

# filtra_linhas_2 = teste['ocean_proximity'] == 'NEAR OCEAN'
# nocean = teste.loc[filtra_linhas_2, :]

# filtra_linhas_3 = teste['ocean_proximity'] == 'NEAR BAY'
# bay = teste.loc[filtra_linhas_3, :]

KeyError: ('longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income')

In [ ]:
# Importando as bibiliotecas necessárias
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
# Definindo nossa coluna de interesse "finalG" e separando ela do DF a ser analisado pelo modelo
labels = np.array(data['preço'])
data = data.drop('preço', axis = 1)

# Fazendo uma lista com as colunas do DF
data_list = list(data.columns)

In [ ]:
# Importando bibliote do RandomForest
from sklearn.ensemble import RandomForestRegressor

# Criando modelo
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
rf.fit(train_data, train_labels)

# Criando previsões
predictions_rf = rf.predict(test_data)